function [t_array, CTFS_syn_array] = CTFS_synthesis(total_range_left, total_range_right, omega0, azero2an, resoln)
%CTFS_SYNTHESIS It outputs the array of the CTFS synthesis
% To plot the synthesized signal, simply use the command 
%  plot(t_array, CTFS_syn_array)
%  Since we assume the output signal is real, the coefficients must be
%  conjugate symmetric. Therefore, the input only needs to be a0, a1, a2,
%  ....  The other half a_{-1}, a_{-2}, ... are automatically generated by
%  conjugate symmetry. 

if(nargin==4)
    resoln=50;
end

if( total_range_left<=total_range_right)
    
    if(imag(azero2an(1,1))~=0)
        error('a0 must be of real value.')
    else

        t_array=total_range_left:(1/resoln):total_range_right;
        CTFS_syn_array=zeros(size(t_array));

        n_order=length(azero2an)-1;

        for(iii=0:n_order)
            if(iii==0)
                CTFS_syn_array=CTFS_syn_array+ones(size(t_array))*real(azero2an(1,1));
            else
                CTFS_syn_array=CTFS_syn_array+2*cos(iii*omega0*t_array)*real(azero2an(1,iii+1)) ...
                    - 2*sin(iii*omega0*t_array)*imag(azero2an(1,iii+1));
            end
        end
    end
else
    error('The input range is incorrect!')
end
end

